# Generated by Django 2.2.1 on 2020-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='作者姓名')),
                ('gender', models.CharField(max_length=32, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name=32)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
    ]
